development: &default
  adapter: mysql2
  encoding: utf8
  database: graphql_dev
  host: localhost
  username: root
  password: ''
  pool: 10
  collation: utf8_unicode_ci

test:
  <<: *default
  database: graphql_test

production:
  <<: *default
  database: graphql_prod
